# Generated by Django 5.0.6 on 2024-06-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role2',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
