# Generated by Django 5.0.6 on 2024-06-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_role2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='role2',
        ),
    ]
