# Generated by Django 5.0.6 on 2024-06-28 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f164f71d-00ef-40e2-9a92-db5205dfa1aa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
