# Generated by Django 5.0.6 on 2024-06-28 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5ec8eb6-bdc1-4ac2-8724-773def336904'), editable=False, primary_key=True, serialize=False),
        ),
    ]
