# Generated by Django 5.0.6 on 2024-06-28 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8154ce6d-789e-480a-b438-61d42e9be9b6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
