# Generated by Django 5.0.6 on 2024-06-28 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a79ac44a-a821-4c57-b0ef-1448856d4d87'), editable=False, primary_key=True, serialize=False),
        ),
    ]
