# Generated by Django 5.0.6 on 2024-06-28 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a992d93-4b75-4c09-8c2d-cd99478b5c57'), editable=False, primary_key=True, serialize=False),
        ),
    ]
