# Generated by Django 5.0.6 on 2024-06-28 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3844fa6c-96a3-4648-bd00-0a847d442adb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
