# Generated by Django 5.0.6 on 2024-06-28 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.UUID('69828b2e-cbe5-44c1-b097-21c06f43d85e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
