# Generated by Django 5.0.6 on 2024-06-28 16:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_id'),
        ('vehicle', '0004_alter_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2ae43b65-5876-45a3-8d09-b272341cd3e7'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('price', models.CharField(max_length=7)),
                ('qty', models.CharField(max_length=7)),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('boarding_point_name', models.CharField(max_length=250)),
                ('dropping_point_name', models.CharField(max_length=250)),
                ('starting_point_name', models.CharField(max_length=250)),
                ('ending_point_name', models.CharField(max_length=250)),
                ('delay', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.category')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
