# Generated by Django 5.0.6 on 2024-06-28 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_id'),
        ('ticket', '0001_initial'),
        ('vehicle', '0005_alter_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_category_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ForeignKey(db_column='ticket_category_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='category.category'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.vehicle'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e92a88a4-9314-4838-9170-77283f5baa36'), editable=False, primary_key=True, serialize=False),
        ),
    ]
